// Generated by scripts/build-hero-ecosystem.mjs from public/images/hero-ecosystem-source.svg.
// Wires are trimmed at both ends - clear of the CORE disc and clear of each
// pill - so they never cross the artwork underneath. Re-run the script rather
// than hand-editing this file; the module list lives in the script.

export interface HeroNode {
  id: string;
  label: string;
  /** A lucide-react export name; HERO_ICONS in HeroEcosystem.tsx resolves it. */
  icon: string;
  pill: { x: number; y: number; w: number; h: number };
  circle: { cx: number; cy: number; r: number };
  iconBox: { x: number; y: number; size: number };
  /** x is the text anchor, w the advance width the label is set to. */
  text: { x: number; w: number };
  line: string;
  lineLength: number;
}

export const HERO_VIEWBOX = "0 0 723 660";

/** Stroke width for a 24-unit lucide icon drawn in a 14-unit box. */
export const HERO_ICON_STROKE = 1.7;

export const HERO_NODES: HeroNode[] = [
  {
    id: "payments",
    label: "Payments",
    icon: "CreditCard",
    pill: { x: 302.55, y: 99.37, w: 117, h: 46 },
    circle: { cx: 325.55, cy: 122.37, r: 14 },
    iconBox: { x: 318.55, y: 115.37, size: 14 },
    text: { x: 349.55, w: 55.09 },
    line: "M361.05 227.94L361.05 147.87",
    lineLength: 80.07,
  },
  {
    id: "automation",
    label: "Automation",
    icon: "Cog",
    pill: { x: 418.81, y: 145.47, w: 130, h: 46 },
    circle: { cx: 441.81, cy: 168.47, r: 14 },
    iconBox: { x: 434.81, y: 161.47, size: 14 },
    text: { x: 465.81, w: 67.6 },
    line: "M405.69 246.91L461.42 193.2",
    lineLength: 77.4,
  },
  {
    id: "digital-banking",
    label: "Digital Banking",
    icon: "MonitorSmartphone",
    pill: { x: 461.17, y: 259.85, w: 147, h: 46 },
    circle: { cx: 484.17, cy: 282.85, r: 14 },
    iconBox: { x: 477.17, y: 275.85, size: 14 },
    text: { x: 508.17, w: 85.08 },
    line: "M423.05 289.94L458.67 289.94",
    lineLength: 35.62,
  },
  {
    id: "compliance",
    label: "Compliance",
    icon: "ShieldCheck",
    pill: { x: 418.81, y: 375.88, w: 130, h: 46 },
    circle: { cx: 441.81, cy: 398.88, r: 14 },
    iconBox: { x: 434.81, y: 391.88, size: 14 },
    text: { x: 465.81, w: 68.47 },
    line: "M405.69 332.96L448.42 374.15",
    lineLength: 59.35,
  },
  {
    id: "technology",
    label: "Technology",
    icon: "Cpu",
    pill: { x: 297.05, y: 428.56, w: 128, h: 46 },
    circle: { cx: 320.05, cy: 451.56, r: 14 },
    iconBox: { x: 313.05, y: 444.56, size: 14 },
    text: { x: 344.05, w: 66.13 },
    line: "M361.05 351.94L361.05 426.06",
    lineLength: 74.12,
  },
  {
    id: "operations",
    label: "Operations",
    icon: "Workflow",
    pill: { x: 175.27, y: 376.16, w: 126, h: 46 },
    circle: { cx: 198.27, cy: 399.16, r: 14 },
    iconBox: { x: 191.27, y: 392.16, size: 14 },
    text: { x: 222.27, w: 63.61 },
    line: "M316.4 332.96L273.38 374.43",
    lineLength: 59.75,
  },
  {
    id: "core-banking",
    label: "Core Banking",
    icon: "Landmark",
    pill: { x: 118.41, y: 256.94, w: 138, h: 46 },
    circle: { cx: 141.41, cy: 279.94, r: 14 },
    iconBox: { x: 134.41, y: 272.94, size: 14 },
    text: { x: 165.41, w: 75.57 },
    line: "M299.05 289.94L258.91 289.94",
    lineLength: 40.14,
  },
  {
    id: "integration",
    label: "Integration",
    icon: "Blocks",
    pill: { x: 175.77, y: 139.11, w: 125, h: 46 },
    circle: { cx: 198.77, cy: 162.11, r: 14 },
    iconBox: { x: 191.77, y: 155.11, size: 14 },
    text: { x: 222.77, w: 62.97 },
    line: "M316.4 246.91L254.07 186.84",
    lineLength: 86.56,
  },
];
